// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7fQDGl9eR2ejZ8P71GLji8G6S2YX7F4w',
    appId: '1:556737415112:web:2bcae32b5210125381e2fd',
    messagingSenderId: '556737415112',
    projectId: 'cryptoapp-87bae',
    authDomain: 'cryptoapp-87bae.firebaseapp.com',
    storageBucket: 'cryptoapp-87bae.firebasestorage.app',
    measurementId: 'G-5N5ZY4CCPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV1lRmelrOWtoENv-7qBVmvNkNWLU7p8g',
    appId: '1:556737415112:android:080a9f446cb47a2881e2fd',
    messagingSenderId: '556737415112',
    projectId: 'cryptoapp-87bae',
    storageBucket: 'cryptoapp-87bae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqS-_LMiTT29cvWaKRQN9tKEfBIb7fVFY',
    appId: '1:556737415112:ios:2678a467ec86341081e2fd',
    messagingSenderId: '556737415112',
    projectId: 'cryptoapp-87bae',
    storageBucket: 'cryptoapp-87bae.firebasestorage.app',
    iosBundleId: 'com.example.cryptoWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqS-_LMiTT29cvWaKRQN9tKEfBIb7fVFY',
    appId: '1:556737415112:ios:2678a467ec86341081e2fd',
    messagingSenderId: '556737415112',
    projectId: 'cryptoapp-87bae',
    storageBucket: 'cryptoapp-87bae.firebasestorage.app',
    iosBundleId: 'com.example.cryptoWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7fQDGl9eR2ejZ8P71GLji8G6S2YX7F4w',
    appId: '1:556737415112:web:1182493e0281a38681e2fd',
    messagingSenderId: '556737415112',
    projectId: 'cryptoapp-87bae',
    authDomain: 'cryptoapp-87bae.firebaseapp.com',
    storageBucket: 'cryptoapp-87bae.firebasestorage.app',
    measurementId: 'G-TXPGYES7KG',
  );
}
